[build]
  # 1. Install & Build Frontend (Root)
  # 2. Go into backend folder -> Install & Build Backend
  command = "npm install && npm run build && cd backend && npm install && npm run build"
  
  # The frontend build output (Vite default is 'dist' in the root)
  publish = "dist"
  
  # The backend build output
  functions = "backend/dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200